/** App chrome wording. A language pack may override any key under `ui`. Not health content. */
export const UI_DEFAULT = {
  add_person: 'Add a person',
  home_title: 'Who are we checking on today?',
  home_sub: 'A weekly check, in her own words.',
  pin_on: 'PIN on',
  replay: 'Replay',
  start: 'Start this week’s session',
  clinic_card: 'Card for the clinic',
  language: 'Language',
  label: 'A name or word for this record',
  pregnant: 'Pregnant',
  after_birth: 'Baby is born',
  due_date: 'Expected date of birth',
  birth_date: 'Date of birth of the baby',
  next_visit: 'Next clinic visit',
  her_phone: 'Her own phone number (for the weekly SMS)',
  tracks: 'What the nurse has told her',
  pin: 'PIN to lock this record (optional)',
  pin_enter: 'Enter PIN',
  wrong_pin: 'That PIN did not open the record.',
  save: 'Save',
  skip: 'Skip',
  back: 'Back',
  next: 'Next',
  finish: 'Finish',
  name: 'Name',
  phone: 'Phone',
  place: 'Name of the place',
  call: 'Call',
  send_sms: 'Send SMS',
  show_pictures: 'Show pictures',
  type_here: 'Or type here',
  send: 'Send',
  draft: 'Draft wording, not yet checked by a speaker or a clinician.',
  device_voice: 'Using the phone’s own voice. Recorded clips are not installed for this language.',
  synthetic_voice: 'Computer-made voice, not yet checked by a speaker.',
  shared_phone: 'Anyone who can open this phone can see this record unless you set a PIN.',
  last_session: 'Last session',
  none_yet: 'No session yet',
  weeks: 'weeks',
  signs_yes: 'Signs she said yes to',
  signs_unsure: 'Signs she was not sure about',
  complaints: 'What she described',
  unanswered: 'Questions the tool could not answer',
  recalled: 'Signs recalled without help',
  plan: 'Her plan',
  delete: 'Delete this record',
  delete_confirm: 'Tap again to delete for good',
  sources: 'Sources',
  send_audio: 'Send the danger-sign audio to her basic phone',
  send_audio_failed: 'The audio could not be sent.',
  teach_voice: 'Teach the phone my voice',
  teach_how: 'Tap a sign, say it in your own words, then tap again. Do each one two or three times. Only this phone keeps it, and no sound is saved.',
  no_voice: 'The speech model is not installed on this phone.',
  mic_unsupported: 'This browser cannot use the microphone. Open AMMA in Chrome (not inside another app) to speak. You can still tap a picture or type.',
  mic_blocked: 'The microphone is blocked for this site. Allow it in the browser settings to speak. You can still tap a picture or type.',
  mic_start: 'Tap and speak',
  mic_stop: 'Tap when you have finished',
  tell_them: 'Tell them now',
  copy: 'Copy message',
  copied: 'Copied',
  share: 'Share',
  print: 'Print',
  share_card: 'Send this card',
  no_sessions: 'No session yet. After the first session, what she reported will show here.',
  last_result: 'Result of the last session',
  find_near: 'Find places near me',
  straight_line: 'km in a straight line, not by road',
  nearest_hospital: 'Nearest hospital on the official list',
  no_coverage: 'No place was found near you. Search by name below, or type the name.',
  no_location: 'The phone could not find its location. Turn on Location, or search by name below.',
  location_denied: 'Location is blocked for this site. Allow it in the browser settings, or search by name below.',
  locating: 'Finding where you are…',
  searching_map: 'Looking on the public map…',
  search_place: 'Or search for a place by name',
  directions: 'Directions',
  unconfirmed: 'from a public map, not an official list',
  not_installed: 'The content pack is not installed.',
} as const;
export type UiKey = keyof typeof UI_DEFAULT;
