/** App chrome wording. A language pack may override any key under `ui`. Not health content. */
export const UI_DEFAULT = {
  add_person: 'Add a person',
  start: 'Start this week’s session',
  clinic_card: 'Card for the clinic',
  language: 'Language',
  label: 'A name or word for this record',
  pregnant: 'Pregnant',
  after_birth: 'Baby is born',
  due_date: 'Expected date of birth',
  birth_date: 'Date of birth of the baby',
  next_visit: 'Next clinic visit',
  her_phone: 'Her own phone number (for the weekly SMS)',
  tracks: 'What the nurse has told her',
  pin: 'PIN to lock this record (optional)',
  pin_enter: 'Enter PIN',
  wrong_pin: 'That PIN did not open the record.',
  save: 'Save',
  skip: 'Skip',
  back: 'Back',
  next: 'Next',
  finish: 'Finish',
  name: 'Name',
  phone: 'Phone',
  place: 'Name of the place',
  call: 'Call',
  send_sms: 'Send SMS',
  show_pictures: 'Show pictures',
  type_here: 'Or type here',
  send: 'Send',
  draft: 'Draft wording, not yet checked by a speaker or a clinician.',
  device_voice: 'Using the phone’s own voice. Recorded clips are not installed for this language.',
  shared_phone: 'Anyone who can open this phone can see this record unless you set a PIN.',
  last_session: 'Last session',
  none_yet: 'No session yet',
  weeks: 'weeks',
  signs_yes: 'Signs she said yes to',
  signs_unsure: 'Signs she was not sure about',
  complaints: 'What she described',
  unanswered: 'Questions the tool could not answer',
  recalled: 'Signs recalled without help',
  plan: 'Her plan',
  delete: 'Delete this record',
  delete_confirm: 'Tap again to delete for good',
  sources: 'Sources',
  teach_voice: 'Teach the phone my voice',
  teach_how: 'Tap a sign, say it in your own words, then tap again. Do each one two or three times. Only this phone keeps it, and no sound is saved.',
  no_voice: 'The speech model is not installed on this phone.',
  mic_start: 'Tap and speak',
  mic_stop: 'Tap when you have finished',
  find_near: 'Find places near me',
  straight_line: 'km in a straight line, not by road',
  nearest_hospital: 'Nearest hospital on the official list',
  no_coverage: 'No facility list is installed for where you are. Type the name.',
  no_location: 'The phone could not give its location. Type the name.',
  unconfirmed: 'from a public map, not an official list',
  not_installed: 'The content pack is not installed.',
} as const;
export type UiKey = keyof typeof UI_DEFAULT;
