"""Hand-written text of the generated write-up. {{NAME}} = generated table/text, {{v:path:fmt}} = a single
value read from the results JSON at build time. No measured number is typed in by hand unless marked."""

TEMPLATE = r"""# Few-shot spoken-intent matching on Wolof without transcription: WolBanking77 measurement

Generated by `uv run fewshot all` (see `research/harness/README.md`). Tables and inline figures are read
from `wolbanking77-fewshot.results.json` when this file is built. Protocol: `protocol.md`, written before
any result was seen; deviations are listed there and in section 9.

## 1. Bottom line

With k recordings per intent and a frozen Whisper-tiny or Whisper-base encoder, mean-pooled and matched
by cosine similarity, **the matcher does not work well enough to use, on this dataset**:

- Best pre-registered configuration ({{BEST}}), new speakers, k=10: macro accuracy
  {{v:grid/base|final|nn/10/A/test_macro/mean:pct1}}% (chance 10%), per-clip accuracy
  {{v:grid/base|final|nn/10/A/test_micro/mean:pct1}}%. At k=1 it is
  {{v:grid/base|final|nn/1/A/test_macro/mean:pct1}}% macro. When the query's sentence was not among the
  support recordings (condition B), k=10 macro accuracy is {{v:grid/base|final|nn/10/B/test_macro/mean:pct1}}%.
- Whisper-tiny and Whisper-base are indistinguishable here (k=10 macro
  {{v:grid/tiny|final|nn/10/A/test_macro/mean:pct1}}% vs {{v:grid/base|final|nn/10/A/test_macro/mean:pct1}}%,
  with an episode standard deviation of about 3 points).
- **Abstention by cosine threshold does not rescue it.** A threshold calibrated on held-out speakers for
  "at most 5% error among accepted" accepts
  {{v:grid/base|final|nn/10/A/abstention/maxsim/calibrated/0.05/coverage/mean:pct1}}% of utterances at k=10,
  and the accepted ones are still wrong
  {{v:grid/base|final|nn/10/A/abstention/maxsim/calibrated/0.05/error_among_accepted_pooled:pct1}}% of the
  time. Even with the threshold chosen on the test data itself (an upper bound), coverage at 5% error is
  {{v:grid/base|final|nn/10/A/abstention/maxsim/oracle_coverage_at_error/0.05/mean:pct1}}%.
- The vectors are not noise. A post-hoc check (section 6) with every recording of 6 other speakers as
  support (about {{v:diagnostics_posthoc/base|final|nn/full_pool_nn/support_clips_mean:f0}} clips, far
  from few-shot) reaches {{v:diagnostics_posthoc/base|final|nn/full_pool_nn/test_macro/mean:pct1}}% macro
  accuracy on new speakers. The matcher behaves more like "have I heard this sentence before?" than
  "what does this mean?": it needs the phrasing to be in the support set, and k examples per intent do
  not cover the 2 to 39 phrasings each intent has in this data.

What this does and does not say about the maternal-health tool is in section 8.

## 2. What the data is, and is not

Source: Hugging Face `karim155/WolBanking77` at revision `{{v:dataset/revision:raw}}` (ungated). The audio
is in that repo, under `WolBanking77/audio/`, as two parquet files with embedded WAV bytes plus two CSVs.
Nothing was substituted. The paper (arXiv 2509.19271) points to `github.com/abdoukarim/wolbanking77`
for code; it was not needed.

{{DATASET_TABLE}}

What it is:

- Wolof **read speech**: a fixed list of sentences, each read aloud by many of the 16 speaker ids
  (file names contain `elicit`, consistent with a prompted-recording app). It is not spontaneous speech.
- Columns: `text` (Wolof sentence), `audio`, `intent`, `duration` (ms), `gender`, `user_id`. No age,
  dialect, device or recording-condition metadata.
- The brief described "263 spoken sentences". What is there: `questions.csv` has 186 customer rows and
  `responses.csv` has 77 bot-response rows (186 + 77 = 263 text rows), but the recorded audio is
  **3,204 clips of 177 distinct sentences**. By exact string match, 128 of the 177 recorded sentences
  appear in `questions.csv` and 18 in `responses.csv`; the other 49 match neither file exactly. We used
  the `text` and `intent` columns of the parquet files as ground truth.
- The 10 intents are banking and transport: balance, cash deposit, card freeze, latest transactions,
  bill payment, amounts (spoken numbers), opening an account, bus reservation, vehicle technical visit,
  money transfer. Classes are very unbalanced:

{{INTENT_TABLE}}

- Speakers are unbalanced too; 6 of the 16 ids did not record every intent, and one id carries two
  different `gender` values:

{{SPEAKER_TABLE}}

What it is not:

- **Not health.** No maternal-health vocabulary or intents.
- **Not pregnant speakers** (nothing says so), not recorded in clinics or homes, and there is no
  information on recording device or background noise.
- **Not a usable official split for this question.** All 16 speakers and 176 of 177 sentences are on both
  sides of the published train/test split, so we pooled both files and split by speaker ourselves.
- **No out-of-scope audio.** Every clip belongs to one of the 10 intents.
- `user_id` is assumed to identify a speaker; we cannot verify that.
- Licence: the dataset card states CC BY 4.0. The encoders (`openai/whisper-tiny`, `openai/whisper-base`)
  are MIT-licensed on their model cards.

## 3. Protocol in brief

Full text in `protocol.md`. In each of 50 seeded episodes the 16 speakers are split 6 / 4 / 6 into
support pool / calibration / test, with no speaker in two groups ({{REDRAWS}} draws were rejected for
not covering all intents). k in {1, 3, 5, 10} support clips per intent are drawn from the support pool.
Encoder vectors are the mean over the encoder frames that cover real audio (not the 30 s padding),
L2-normalised. Two classifiers: prototype-mean, and nearest-neighbour over all support clips.

- **Condition A**: every clip of the 6 test speakers (about {{v:grid/base|final|nn/1/A/n_test_mean:f0}} per
  episode). The same sentence, read by someone else, may be in the support set.
- **Condition B**: only test clips whose sentence is not in the support set. At larger k the intents with
  few sentences drop out, so B is over fewer intents (column "B intents left").

The configuration used for robustness and export was chosen by macro accuracy on the calibration
speakers only. Thresholds for abstention were chosen on calibration speakers and applied to test
speakers; "oracle" numbers choose the threshold on the test data and are upper bounds.

## 4. Accuracy without abstention

Mean ± standard deviation over 50 episodes, test speakers. Chance is 10% macro; always answering the
largest intent gives 22.5% micro. Best layer per encoder (chosen on calibration speakers), both classifiers:

{{HEADLINE_TABLE}}

At k=1 the two classifiers are the same thing. Nearest-neighbour beats prototype-mean at k>=3 for the
final layer: averaging recordings of different sentences into one prototype loses information here.

All grid cells (macro accuracy %, test speakers; the selection score is from calibration speakers):

{{GRID_TABLE}}

Selected configuration: **{{BEST}}**. Its lead over whisper-tiny / final / nn on the selection score
({{v:selection/scores/base|final|nn:pct2}}% vs {{v:selection/scores/tiny|final|nn:pct2}}%) is well inside the
episode-to-episode spread, so this is not evidence that base is better than tiny.

## 5. Abstention: risk-coverage

Confidence = top cosine similarity (what the brief asked for). Selective error (% wrong among accepted)
when the most confident share of test utterances is accepted; selected configuration, condition A:

{{RC_MAXSIM_A}}

Coverage at low error, condition A, cosine-similarity threshold. "Oracle" = threshold chosen on the test
utterances (upper bound). "Calibrated" = threshold chosen on 4 other speakers and applied to the test
speakers; the three numbers are mean coverage %, realised error % among accepted (pooled over the 50
episodes), and the share of episodes (%) whose realised error was above the target:

{{ABSTAIN_MAXSIM_A}}

The 0% and 1% columns are nearly identical because the accepted sets are tiny (a 1% budget allows no
error at all until 100 clips are accepted). Calibrated thresholds do not hold their target on new
speakers: realised error is roughly two to three times the 5% target, and far above the 0% and 1%
targets, in about half or more of the episodes.

Condition B (query sentence not in the support set), same layout:

{{ABSTAIN_MAXSIM_B}}

Secondary confidence score from the protocol, the margin between the best and second-best intent. Same
selected configuration, condition A, risk-coverage and then coverage at low error:

{{RC_MARGIN_A}}

{{ABSTAIN_MARGIN_A}}

The margin ranks answers better than raw similarity at k=10, but coverage at 5% error stays in single
digits and the calibrated threshold still overshoots its target.

**No configuration reaches useful coverage at 0%, 1% or 5% error.** With roughly 1,100 test clips per
episode, coverage below about 1% is a handful of clips and should be read as "effectively zero".

## 6. Post-hoc diagnostics (NOT in the pre-registered protocol)

Added after seeing sections 4 and 5, to tell "too few examples" apart from "the vectors carry no intent
information" and to rule out a pipeline bug. These are exploratory; nothing was selected using them.

{{DIAG_TABLE_1}}

- "Nearest other clip" uses all 3,204 clips, including the same speaker, so it is optimistic.
- "Full-pool 1-NN": support = every clip of the 6 support-pool speakers; test = the 6 test speakers,
  same 50 episodes. Speaker-held-out but not few-shot (about 125 recordings per intent on average).
- All clip vectors sit in a narrow cone (mean pairwise cosine about 0.85). That is consistent with a raw
  cosine threshold separating right from wrong answers so poorly.

Mean-centring (subtract the mean vector of the support-pool speakers' clips, then re-normalise), applied
to the pre-registered few-shot task:

{{DIAG_TABLE_2}}

Centring moves accuracy by about one to three points and does not change the conclusion.

## 7. Robustness, size and speed

### 7.1 Degraded audio (selected configuration, condition A)

`tel8k` = resampled to 8 kHz and back (band-limit only: no 300 Hz high-pass, no codec). `noise10` = white
Gaussian noise at 10 dB SNR. "mismatched" = clean support recordings, degraded queries; "matched" =
everything degraded. Deltas are against the clean row with the same k.

{{ROBUST_TABLE}}

Band-limiting to 4 kHz costs a few points (k=10, clean support:
{{v:grid/base|final|nn/10/A/test_macro/mean:pct1}}% to
{{v:robustness/conditions/tel8k|mismatched/10/A/test_macro/mean:pct1}}% macro). White noise at 10 dB SNR
costs more (k=10: {{v:robustness/conditions/noise10|mismatched/10/A/test_macro/mean:pct1}}% with clean
support, {{v:robustness/conditions/noise10|matched/10/A/test_macro/mean:pct1}}% when the support recordings
are noisy too). Recording the support examples under the same degradation did not help in either case.
These deltas sit on top of a clean baseline that is already too low.

### 7.2 ONNX export, int8, latency

Encoder only (whisper-base, {{v:onnx/params_full_encoder:raw}} parameters), fixed 30 s log-mel input
`(1, 80, 3000)`. int8 = onnxruntime dynamic quantisation of MatMul weights; the two convolutions and the
positional table stay fp32. Export: {{ONNX_NOTES}}. ONNX fp32 against PyTorch pooled vectors: {{PARITY}}.
ONNX int8 against PyTorch fp32 pooled vectors: cosine {{INT8_COS}}.

{{ONNX_SIZE_TABLE}}

Latency for one 5.0 s clip on this machine (AMD Ryzen 5 5625U laptop, onnxruntime CPU; median and p90 of
30 runs after 5 warm-ups). "End-to-end" = log-mel + encoder + pooling; log-mel alone has a median of about
{{LOGMEL_MS}} ms. The encoder always processes 30 s of padded input, so latency does not depend on clip
length. The machine was not idle (a desktop session with a browser was running; 1-minute load average
{{v:onnx/latency/load_average_1min_at_measurement:f2}} when measured), so treat these as approximate;
differences of a few percent between rows are noise:

{{ONNX_LATENCY_TABLE}}

Accuracy of the int8 model on the same task (all 3,204 clips re-embedded with the int8 ONNX encoder,
same episodes):

{{ONNX_INT8_TABLE}}

int8 quantisation changes accuracy by a fraction of a point, well inside the episode spread, and cuts
the file to about a third. Whisper-tiny was not exported (the protocol exports only the selected
encoder); given that it matched whisper-base on accuracy, it would be the natural choice on size, and
its ONNX size and latency remain unmeasured here.

## 8. Limits

- **The dataset is too small and too narrow for any claim about a health tool.** 16 speaker ids, 177
  read sentences, 10 banking/transport intents, about 4.3 hours. Nothing here is health vocabulary,
  nothing is spontaneous speech, none of the speakers is known to be pregnant, and recording conditions
  are unknown.
- **What can be claimed:** on this data, k <= 10 recordings per intent with mean-pooled frozen
  Whisper-tiny/base vectors gives accuracy far below what a health tool needs, and a cosine threshold
  does not buy low error at any useful coverage. That is a negative result about this particular recipe
  (mean pooling, no training, broad intents with many phrasings), measured on one small dataset.
- **What cannot be claimed:** that the idea fails in general; that it would fail when each "meaning" is
  one short fixed phrase; that it works or fails in Hindi or Marathi (not measured); how it behaves on
  real phone audio, real background noise, or far-field speech.
- **Intent granularity mismatch.** A WolBanking77 intent is a broad category covering 2 to 39 different
  sentences. The tool's "one of N known meanings" may be closer to one phrase per meaning. Section 6
  suggests the matcher behaves like a phrase matcher. That case (177 sentence classes, k recordings of
  the same sentence by other speakers) was not in the pre-registered protocol and was not measured as a
  few-shot task. It is the obvious next experiment and this dataset supports it.
- **Abstention was only tested on in-scope audio.** There are no out-of-scope utterances, so "abstain
  when the meaning is unknown", which matters most for safety, is not measured at all.
- **Speakers rotate between roles.** Across episodes the same speaker is support in one, calibration in
  another and test in a third. Episodes are therefore correlated; the ± values describe spread over
  splits of these 16 speakers and are not confidence intervals for a new population. Model selection
  used calibration speakers only within an episode, but those speakers are test speakers in other
  episodes, so the selected cell's test numbers are very slightly optimistic. All 20 cells are reported.
- **Speaker identity is taken from `user_id`**; if two ids are one person, the hold-out is weaker than
  stated.
- **Robustness is synthetic**: band-limiting and white noise, not a phone channel, a codec, or real
  background noise.
- **Latency is for one laptop CPU** under a shared desktop load, not a phone. Arm phone numbers will
  differ and were not measured. The 30 s padding is the dominant cost and was not optimised.
- **Not tried** (so no claim either way): attention or learned pooling, a small trained projection head,
  frame-level matching (DTW), other small encoders, Whisper encoders fed less than 30 s, any fine-tuning.

## 9. Deviations from the protocol

1. **Layer grid.** The protocol listed `L1..Ln` (output of each block before the final LayerNorm) plus
   `final`. `transformers` does not expose the last block's output before the final LayerNorm: its last
   hidden state already is `final`. So `Ln` and `final` were the same tensor, and the grid is `L1..L(n-1)`
   plus `final`: 4 layers for tiny, 6 for base, 20 cells instead of 24. The first grid run contained the
   duplicate under both names with identical numbers; the duplicate label was removed and the grid stage
   re-run from the cached vectors. No result changed and the selected configuration is the same tensor.
2. **Post-hoc diagnostics** (section 6) were added after the main results were seen. They are labelled
   as such and were not used for selection.
3. **Latency** was measured while other desktop processes were running, not on an idle machine.
4. Because the selected layer is `final`, only the full encoder was exported (the protocol's truncated
   export applies only to an intermediate layer).

## 10. Reproduction

`cd research/harness && uv run fewshot all`. Environment for this run: {{ENV}}. Wall-clock seconds of
the most recent run of each stage (some ran with embeddings or ONNX files already cached, so these
understate a cold run): {{STAGE_SECONDS}}.
"""
